/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2018-06-21 13:44:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/header.jsp", Long.valueOf(1524040101698L));
    _jspx_dependants.put("jar:file:/D:/学习/java/项目/掌上租/zsz/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ZuFront/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1473930048353L));
    _jspx_dependants.put("/WEB-INF/loading.jsp", Long.valueOf(1474708294482L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("<head>\r\n");
      out.write("    ");
      out.write('\r');
      out.write('\n');
String ctxPath = request.getContextPath(); 
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=no\">    \r\n");
      out.write("    <meta name=\"keywords\" content=\"\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <script src=\"");
      out.print(ctxPath );
      out.write("/js/rem.js\"></script> \r\n");
      out.write("    <script src=\"");
      out.print(ctxPath );
      out.write("/js/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("     <script type=\"text/javascript\" src=\"");
      out.print(ctxPath );
      out.write("/js/menu.js\" ></script>\r\n");
      out.write("     <script type=\"text/javascript\" src=\"");
      out.print(ctxPath );
      out.write("/lib/jquery/1.9.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(ctxPath );
      out.write("/lib/Validform/5.3.2/Validform.min.js\"></script> \r\n");
      out.write("    \r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ctxPath );
      out.write("/lib/layer/1.9.3/layer.js\"></script> \r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ctxPath );
      out.write("/lib/My97DatePicker/WdatePicker.js\"></script> \r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ctxPath );
      out.write("/lib/laypage/1.2/laypage.js\"></script> \r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ctxPath );
      out.write("/lib/datatables/1.10.0/jquery.dataTables.min.js\"></script> \r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ctxPath );
      out.write("/css/base.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ctxPath );
      out.write("/css/page.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ctxPath );
      out.write("/css/all.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ctxPath );
      out.write("/css/mui.min.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ctxPath );
      out.write("/css/loaders.min.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ctxPath );
      out.write("/css/loading.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ctxPath );
      out.write("/slick/slick.css\"/>\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(window).load(function(){\r\n");
      out.write("\t\t\t$(\".loading\").addClass(\"loader-chanage\")\r\n");
      out.write("\t\t\t$(\".loading\").fadeOut(300)\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>");
      out.write("\r\n");
      out.write("\t <title>首页</title>\r\n");
      out.write("\t <script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t $(function(){\r\n");
      out.write("\t\t var cityName;\r\n");
      out.write("\t\t $.ajax({\r\n");
      out.write("\t\t\t\turl:\"http://restapi.amap.com/v3/ip?key=4419e12c11fecf797ad9e437dd323a66&output=JSON\",\r\n");
      out.write("\t\t\t\ttype:\"GET\",\r\n");
      out.write("\t\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\t\tif(result.status==1){\r\n");
      out.write("\t\t\t\t\t\tcityName = result.city;\r\n");
      out.write("\t\t\t\t\t\t//拿到这个城市的名称，然后传到服务器中\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$.ajax({type:\"post\",url:\"");
      out.print(ctxPath);
      out.write("/Index\",\r\n");
      out.write("\t\t\t\t\t\t \tdata:{action:\"queryCurrentCity\",localCityName:cityName},\r\n");
      out.write("\t\t\t\t\t\t \tsuccess:function(city){\r\n");
      out.write("\t\t\t\t\t\t \t\tif(city.status==\"ok\")\r\n");
      out.write("\t\t\t\t\t \t\t\t{\r\n");
      out.write("\t\t\t\t\t \t\t\t\t$(\"#cityName\").text(city.data);\r\n");
      out.write("\t\t\t\t\t \t\t\t}\r\n");
      out.write("\t\t\t\t\t \t\t\telse\r\n");
      out.write("\t\t\t\t\t \t\t\t{\r\n");
      out.write("\t\t\t\t\t \t\t\t\talert(city.msg);\r\n");
      out.write("\t\t\t\t\t \t\t\t}\r\n");
      out.write("\t\t\t\t\t\t \t},\r\n");
      out.write("\t\t\t\t\t\t \terror:function(){\r\n");
      out.write("\t\t\t\t\t\t \t\talert(\"获取当前城市网络请求失败\");\r\n");
      out.write("\t\t\t\t\t\t \t}\r\n");
      out.write("\t\t\t\t\t\t });\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tlayer.msg(\"城市定位失败\"+result.info,{icon:6,time:1000});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror:function(){\r\n");
      out.write("\t\t\t\t\tlayer.msg(\"城市定位失败\"+result.info,{icon:6,time:1000});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t $(\"#btnChangeCity\").click(function(){\r\n");
      out.write("\t\t\t var left = $(this).offset().left;\r\n");
      out.write("\t\t\t var top = $(this).offset().top;\r\n");
      out.write("\t\t\t var height = $(this).height();\r\n");
      out.write("\t\t\t var width = $(this).width();\r\n");
      out.write("\t\t\t $(\"#citiesList\").toggle(\"fast\").css(\"left\",left).css(\"top\",top+height);\r\n");
      out.write("\t\t });\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t $(\"#citiesList li\").click(function(){\r\n");
      out.write("\t\t\t var cityId = $(this).attr(\"cityId\");\r\n");
      out.write("\t\t\t $.ajax({\r\n");
      out.write("\t\t\t\t type:\"post\",url:\"");
      out.print(ctxPath);
      out.write("/Index\",\r\n");
      out.write("\t\t\t\t data:{action:\"changeCity\",cityId:cityId},\r\n");
      out.write("\t\t\t\t success:function(result)\r\n");
      out.write("\t\t\t\t {\r\n");
      out.write("\t\t\t\t\t if(result.status==\"ok\")\r\n");
      out.write("\t\t\t\t\t {\r\n");
      out.write("\t\t\t\t\t \tlocation.reload();//刷新页面\r\n");
      out.write("\t\t\t\t\t }\r\n");
      out.write("\t\t\t\t\t else\r\n");
      out.write("\t\t\t\t\t {\r\n");
      out.write("\t\t\t\t\t \talert(result.msg);\r\n");
      out.write("\t\t\t\t\t }\r\n");
      out.write("\t\t\t\t },\r\n");
      out.write("\t\t\t\t error:function()\r\n");
      out.write("\t\t\t\t {\r\n");
      out.write("\t\t\t\t\t alert(\"切换城市网络请求失败\");\r\n");
      out.write("\t\t\t\t }\r\n");
      out.write("\t\t\t });\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t });\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t $(\"#txtSearch\").keydown(function(e){\r\n");
      out.write("\t\t\t if(e.keyCode==13)//按了回车\r\n");
      out.write("\t\t\t {\r\n");
      out.write("\t\t\t \tlocation.href=\"");
      out.print(ctxPath);
      out.write("/House?action=search&keywords=\"+encodeURI($(this).val());\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t });\r\n");
      out.write("\t });\r\n");
      out.write("\t </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!--loading页开始-->\r\n");
      out.write("<div class=\"loading\">\r\n");
      out.write("\t<div class=\"loader\">\r\n");
      out.write("        <div class=\"loader-inner pacman\">\r\n");
      out.write("          <div></div>\r\n");
      out.write("          <div></div>\r\n");
      out.write("          <div></div>\r\n");
      out.write("          <div></div>\r\n");
      out.write("          <div></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--loading页结束-->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<body>\r\n");
      out.write("\t<div style=\"display:none;position:absolute;z-index: 300;background-color: white;cursor: pointer;\" id=\"citiesList\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!--header star-->\r\n");
      out.write("\t\t<div class=\"header clearfloat\">\r\n");
      out.write("\t\t\t<div class=\"tu clearfloat\">\r\n");
      out.write("\t\t\t\t<img src=\"img/index-banner.jpg\"/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<header class=\"mui-bar mui-bar-nav\">\r\n");
      out.write("\t\t\t\t<a class=\"btn\" href=\"#\" id=\"btnChangeCity\">\t\t            \r\n");
      out.write("\t\t            <p><b id='cityName'>北京</b><i class=\"iconfont icon-iconfontarrowdown-copy\"></i></p>\r\n");
      out.write("\t\t        </a>\r\n");
      out.write("\t\t        <div class=\"top-sch-box flex-col\">\r\n");
      out.write("\t\t            <div class=\"centerflex\">\r\n");
      out.write("\t\t                <i class=\"fdj iconfont icon-sousuo\"></i>\r\n");
      out.write("\t\t                <div class=\"sch-txt\">请输入您要搜索的内容</div>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t    </header>\r\n");
      out.write("\t\t    <div class=\"header-tit clearfloat\">\r\n");
      out.write("\t\t    \t<p class=\"header-num\">掌上租已为<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${houseAppTotalCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>用户成功租房！</p>\r\n");
      out.write("\t\t    \t<p class=\"header-da\">轻松租房  乐享生活</p>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--header end-->\r\n");
      out.write("\t\t<div id=\"main\" class=\"mui-clearfix\">\r\n");
      out.write("\t\t \t<!-- 搜索层 -->\r\n");
      out.write("\t\t    <div class=\"pop-schwrap\">\r\n");
      out.write("\t\t        <div class=\"ui-scrollview\">\r\n");
      out.write("\t\t        \t<div class=\"poo-mui clearfloat box-s\">\r\n");
      out.write("\t\t        \t\t<div class=\"mui-bar mui-bar-nav clone poo-muitwo\">\r\n");
      out.write("\t\t\t                <div class=\"top-sch-box flex-col\">\r\n");
      out.write("\t\t\t                    <div class=\"centerflex\">\r\n");
      out.write("\t\t\t                    \t<i class=\"fdj iconfont icon-sousuo\"></i>\r\n");
      out.write("\t\t\t                        <input class=\"sch-input mui-input-clear\" type=\"text\" name=\"\" id=\"txtSearch\" placeholder=\"请输入您要搜索的内容\" />\r\n");
      out.write("\t\t\t                    </div>\r\n");
      out.write("\t\t\t                </div>\t\t\t                \r\n");
      out.write("\t\t\t            </div>\r\n");
      out.write("\t\t\t            <a href=\"javascript:;\" class=\"mui-btn mui-btn-primary btn-back\" href=\"#\">取消</a>\r\n");
      out.write("\t\t        \t</div>\t\t            \r\n");
      out.write("\t\t            <div class=\"scroll-wrap\">\r\n");
      out.write("\t\t                <div class=\"mui-scroll\">\r\n");
      out.write("\t\t                    <div class=\"sch-cont\">\r\n");
      out.write("\t\t                        <div class=\"section ui-border-b\">\r\n");
      out.write("\t\t                            <div class=\"tit\">热门搜索</div>\r\n");
      out.write("\t\t                            <div class=\"tags\">\r\n");
      out.write("\t\t                                <span class=\"tag\">短租</span><span class=\"tag\">大溪地</span><span class=\"tag\">停车场</span>\r\n");
      out.write("\t\t                                <span class=\"tag\">三房一厅</span><span class=\"tag\">合租</span><span class=\"tag\">经济房</span>\r\n");
      out.write("\t\t                                <span class=\"tag\">写字楼</span><span class=\"tag\">转户</span><span class=\"tag\">整租</span>\r\n");
      out.write("\t\t                            </div>\r\n");
      out.write("\t\t                        </div>\r\n");
      out.write("\t\t                    </div>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    <div class=\"cation clearfloat\">\r\n");
      out.write("\t\t    \t<ul class=\"clearfloat\">\r\n");
      out.write("\t\t    \t\t<li>\r\n");
      out.write("\t\t    \t\t\t<a href=\"");
      out.print(ctxPath );
      out.write("/House?action=search&typeId=14\">\r\n");
      out.write("\t\t\t    \t\t\t<img src=\"img/fang.png\" />\r\n");
      out.write("\t\t\t    \t\t\t<p>整租</p>\r\n");
      out.write("\t\t    \t\t\t</a>\r\n");
      out.write("\t\t    \t\t</li>\r\n");
      out.write("\t\t    \t\t<li>\r\n");
      out.write("\t\t    \t\t\t<a href=\"");
      out.print(ctxPath );
      out.write("/House?action=search&typeId=13\">\r\n");
      out.write("\t\t\t    \t\t\t<img src=\"img/chuang.png\" />\r\n");
      out.write("\t\t\t    \t\t\t<p>合租</p>\r\n");
      out.write("\t\t    \t\t\t</a>\r\n");
      out.write("\t\t    \t\t</li>\r\n");
      out.write("\t\t    \t\t<li>\r\n");
      out.write("\t\t    \t\t\t<a href=\"");
      out.print(ctxPath );
      out.write("/House?action=search&typeId=11\">\r\n");
      out.write("\t\t\t    \t\t\t<img src=\"img/bao.png\" />\r\n");
      out.write("\t\t\t    \t\t\t<p>短租</p>\r\n");
      out.write("\t\t    \t\t\t</a>\r\n");
      out.write("\t\t    \t\t</li>\r\n");
      out.write("\t\t    \t\t<li>\r\n");
      out.write("\t\t    \t\t\t<a href=\"");
      out.print(ctxPath );
      out.write("/House?action=search&typeId=12\">\r\n");
      out.write("\t\t\t    \t\t\t<img src=\"img/lou.png\" />\r\n");
      out.write("\t\t\t    \t\t\t<p>写字楼</p>\r\n");
      out.write("\t\t    \t\t\t</a>\r\n");
      out.write("\t\t    \t\t</li>\r\n");
      out.write("\t\t    \t\t<li>\r\n");
      out.write("\t\t    \t\t\t<a href=\"map.html\">\r\n");
      out.write("\t\t\t    \t\t\t<img src=\"img/map.png\" />\r\n");
      out.write("\t\t\t    \t\t\t<p>地图找房</p>\r\n");
      out.write("\t\t    \t\t\t</a>\r\n");
      out.write("\t\t    \t\t</li>\r\n");
      out.write("\t\t    \t\t<li>\r\n");
      out.write("\t\t    \t\t\t<a href=\"landlord.html\">\r\n");
      out.write("\t\t\t    \t\t\t<img src=\"img/people.png\" />\r\n");
      out.write("\t\t\t    \t\t\t<p>我是房东</p>\r\n");
      out.write("\t\t    \t\t\t</a>\r\n");
      out.write("\t\t    \t\t</li>\r\n");
      out.write("\t\t    \t\t<li>\r\n");
      out.write("\t\t    \t\t\t<a href=\"");
      out.print(ctxPath);
      out.write("/Merchant?action=Apply\">\r\n");
      out.write("\t\t\t    \t\t\t<img src=\"img/woshou.png\" />\r\n");
      out.write("\t\t\t    \t\t\t<p>加盟</p>\r\n");
      out.write("\t\t    \t\t\t</a>\r\n");
      out.write("\t\t    \t\t</li>\r\n");
      out.write("\t\t    \t\t<li>\r\n");
      out.write("\t\t    \t\t\t<a href=\"");
      out.print(ctxPath);
      out.write("/Merchant?action=LifeService\">\r\n");
      out.write("\t\t\t    \t\t\t<img src=\"img/self.png\" />\r\n");
      out.write("\t\t\t    \t\t\t<p>生活服务</p>\r\n");
      out.write("\t\t    \t\t\t</a>\r\n");
      out.write("\t\t    \t\t</li>\r\n");
      out.write("\t\t    \t</ul>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    <div class=\"recom clearfloat\">\r\n");
      out.write("\t\t    \t<div class=\"recom-tit clearfloat box-s\">\r\n");
      out.write("\t\t    \t\t<p>热门房源推荐</p>\r\n");
      out.write("\t\t    \t</div>\r\n");
      out.write("\t\t    \t");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/index.jsp(210,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/index.jsp(210,7) '${recommHouses}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${recommHouses}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/index.jsp(210,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("item");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t    \t<div class=\"content clearfloat box-s\">\r\n");
            out.write("\t\t\t    \t\t<div class=\"list clearfloat fl box-s\">\r\n");
            out.write("\t\t\t    \t\t\t<a href=\"");
            out.print(ctxPath);
            out.write("/House?action=view&id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("\t\t\t\t    \t\t\t<div class=\"tu clearfloat\">\r\n");
            out.write("\t\t\t\t    \t\t\t\t<span></span>\r\n");
            out.write("\t\t\t\t    \t\t\t\t<img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.firstThumbUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"/>\r\n");
            out.write("\t\t\t\t    \t\t\t</div>\r\n");
            out.write("\t\t\t\t    \t\t\t<div class=\"right clearfloat\">\r\n");
            out.write("\t\t\t\t    \t\t\t\t<div class=\"tit clearfloat\">\r\n");
            out.write("\t\t\t\t    \t\t\t\t\t<p class=\"fl\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.communityName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("\t\t\t\t    \t\t\t\t\t<span class=\"fr\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.monthRent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("<samp>元/月</samp></span>\r\n");
            out.write("\t\t\t\t    \t\t\t\t</div>\r\n");
            out.write("\t\t\t\t    \t\t\t\t<p class=\"recom-jianjie\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.roomTypeName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("   |  ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.area}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("m²  |  ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.decorateStatusName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("\t\t\t\t    \t\t\t\t<div class=\"recom-bottom clearfloat\">\r\n");
            out.write("\t\t\t\t    \t\t\t\t\t<span><i class=\"iconfont icon-duihao\"></i>随时住</span>\r\n");
            out.write("\t\t\t\t    \t\t\t\t\t<span><i class=\"iconfont icon-duihao\"></i>家电齐全</span>\r\n");
            out.write("\t\t\t\t    \t\t\t\t</div>\r\n");
            out.write("\t\t\t\t    \t\t\t</div>\r\n");
            out.write("\t\t\t    \t\t\t</a>\r\n");
            out.write("\t\t\t    \t\t</div>\r\n");
            out.write("\t\t\t    \t</div>\r\n");
            out.write("\t\t    \t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      }
      out.write("\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t   </div>\r\n");
      out.write("\t   \r\n");
      out.write("\t   <footer class=\"page-footer fixed-footer\" id=\"footer\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"active\">\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(ctxPath);
      out.write("/Index?action=index\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"iconfont icon-shouyev1\"></i>\r\n");
      out.write("\t\t\t\t\t\t<p>首页</p>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(ctxPath);
      out.write("/Index?action=lease\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"iconfont icon-chuzuwo\"></i>\r\n");
      out.write("\t\t\t\t\t\t<p>我要出租</p>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(ctxPath);
      out.write("/Index?action=schedule\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"iconfont icon-richengbiao\"></i>\r\n");
      out.write("\t\t\t\t\t\t<p>看房日程</p>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(ctxPath);
      out.write("/User?action=center\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"iconfont icon-gerenzhongxin\"></i>\r\n");
      out.write("\t\t\t\t\t\t<p>个人中心</p>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t</body>\r\n");
      out.write("\t<script src=\"js/fastclick.js\"></script>\r\n");
      out.write("\t<script src=\"js/mui.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/hmt.js\" ></script>\r\n");
      out.write("\t<!--插件-->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/swiper.min.css\">\r\n");
      out.write("\t<script src=\"js/swiper.jquery.min.js\"></script>\r\n");
      out.write("\t<!--插件-->\r\n");
      out.write("\r\n");
      out.write("\t<!--搜索点击效果-->\r\n");
      out.write("\t<script >\r\n");
      out.write("\t    $(function () {\r\n");
      out.write("\t        var banner = new Swiper('.banner',{\r\n");
      out.write("\t            autoplay: 5000,\r\n");
      out.write("\t            pagination : '.swiper-pagination',\r\n");
      out.write("\t            paginationClickable: true,\r\n");
      out.write("\t            lazyLoading : true,\r\n");
      out.write("\t            loop:true\r\n");
      out.write("\t        });\r\n");
      out.write("\t\r\n");
      out.write("\t         mui('.pop-schwrap .sch-input').input();\r\n");
      out.write("\t        var deceleration = mui.os.ios?0.003:0.0009;\r\n");
      out.write("\t         mui('.pop-schwrap .scroll-wrap').scroll({\r\n");
      out.write("\t                bounce: true,\r\n");
      out.write("\t                indicators: true,\r\n");
      out.write("\t                deceleration:deceleration\r\n");
      out.write("\t        });\r\n");
      out.write("\t        $('.top-sch-box .fdj,.top-sch-box .sch-txt,.pop-schwrap .btn-back').on('click',function () {\r\n");
      out.write("\t            $('html,body').toggleClass('holding');\r\n");
      out.write("\t            $('.pop-schwrap').toggleClass('on');\r\n");
      out.write("\t            if($('.pop-schwrap').hasClass('on')) {;\r\n");
      out.write("\t                $('.pop-schwrap .sch-input').focus();\r\n");
      out.write("\t            }\r\n");
      out.write("\t        });\r\n");
      out.write("\t\r\n");
      out.write("\t        $.ajax({\r\n");
      out.write("\t        \r\n");
      out.write("\t        });\r\n");
      out.write("\t    });\r\n");
      out.write("\t</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/index.jsp(93,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/index.jsp(93,2) '${cities}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${cities}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/index.jsp(93,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("city");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<li cityId=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${city.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${city.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</li>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
