/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2018-06-21 13:44:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.merchant;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/header.jsp", Long.valueOf(1524040101698L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("<head>\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
String ctxPath = request.getContextPath(); 
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=no\">    \r\n");
      out.write("    <meta name=\"keywords\" content=\"\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <script src=\"");
      out.print(ctxPath );
      out.write("/js/rem.js\"></script> \r\n");
      out.write("    <script src=\"");
      out.print(ctxPath );
      out.write("/js/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("     <script type=\"text/javascript\" src=\"");
      out.print(ctxPath );
      out.write("/js/menu.js\" ></script>\r\n");
      out.write("     <script type=\"text/javascript\" src=\"");
      out.print(ctxPath );
      out.write("/lib/jquery/1.9.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(ctxPath );
      out.write("/lib/Validform/5.3.2/Validform.min.js\"></script> \r\n");
      out.write("    \r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ctxPath );
      out.write("/lib/layer/1.9.3/layer.js\"></script> \r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ctxPath );
      out.write("/lib/My97DatePicker/WdatePicker.js\"></script> \r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ctxPath );
      out.write("/lib/laypage/1.2/laypage.js\"></script> \r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ctxPath );
      out.write("/lib/datatables/1.10.0/jquery.dataTables.min.js\"></script> \r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ctxPath );
      out.write("/css/base.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ctxPath );
      out.write("/css/page.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ctxPath );
      out.write("/css/all.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ctxPath );
      out.write("/css/mui.min.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ctxPath );
      out.write("/css/loaders.min.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ctxPath );
      out.write("/css/loading.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(ctxPath );
      out.write("/slick/slick.css\"/>\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(window).load(function(){\r\n");
      out.write("\t\t\t$(\".loading\").addClass(\"loader-chanage\")\r\n");
      out.write("\t\t\t$(\".loading\").fadeOut(300)\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>");
      out.write("\r\n");
      out.write("\t<script src=\"");
      out.print(ctxPath);
      out.write("/js/swfupload.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(ctxPath);
      out.write("/js/handlers.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=no\">    \r\n");
      out.write("    <meta name=\"keywords\" content=\"\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(window).load(function(){\r\n");
      out.write("\t\t\t$(\".loading\").addClass(\"loader-chanage\")\r\n");
      out.write("\t\t\t$(\".loading\").fadeOut(300)\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar swfu;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tswfu = new \tSWFUpload({\r\n");
      out.write("\t\t\t\t//上传文件的路径\r\n");
      out.write("\t\t\t    upload_url: \"");
      out.print(ctxPath);
      out.write("/Merchant/UploadFile\",\r\n");
      out.write("\t\t\t    flash_url : \"");
      out.print(ctxPath);
      out.write("/js/swfupload.swf\",\r\n");
      out.write("\r\n");
      out.write("\t\t\t    post_params : {\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t    },\r\n");
      out.write("\t\t\t    file_size_limit : \"2 MB\",\r\n");
      out.write("\t\t\t    file_types : \"*.jpg;*.bmp;*.jpg;*.jpeg;*.png;*.gif\",\r\n");
      out.write("\t\t\t    file_types_description : \"JPG Images;bmp Images;jpg Images;jpeg Images;png Images;gif Images\",\r\n");
      out.write("\t\t\t    file_upload_limit : 0,\r\n");
      out.write("                upload_error_handler : uploadError,\r\n");
      out.write("                upload_success_handler : uploadSuccess,\r\n");
      out.write("\r\n");
      out.write("                button_placeholder_id : \"spanButtonPlaceholder\",\r\n");
      out.write("                button_width: 160,\r\n");
      out.write("                button_height: 22,\r\n");
      out.write("                button_text : '<input type=\"button\" name=\"uploadIDCard\">上传文件<span class=\"buttonSmall\">(2 MB Max)</span>',\r\n");
      out.write("                button_text_style : '.button { font-family: Helvetica, Arial, sans-serif; font-size: 14pt; } .buttonSmall { font-size: 10pt; }',\r\n");
      out.write("                button_text_top_padding: 1,\r\n");
      out.write("                button_text_left_padding: 5,\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("                // Debug Settings\r\n");
      out.write("                debug: false\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//文件上传成功后,给用户提示信息\r\n");
      out.write("            function uploadSuccess(file, serverData) {\r\n");
      out.write("                var result = serverData.split('|');\r\n");
      out.write("                if (result[0] == 'ok') {\r\n");
      out.write("                    alert(result[1]);\r\n");
      out.write("                }\r\n");
      out.write("            }\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//文件上传失败，给用户提示信息\r\n");
      out.write("\t\t\tfunction uploadError(){\r\n");
      out.write("\t\t\t\tvar result = serverData.split('|');\r\n");
      out.write("                if (result[0] != 'ok') {\r\n");
      out.write("                    alert(result[1]);\r\n");
      out.write("                }\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t$(\"#btnSubmit\").click(function(){\r\n");
      out.write("\t\t\tvar bossName = $(\"#bossName\").val();\r\n");
      out.write("\t\t\tvar phone = $(\"#PhoneNum\").val();\r\n");
      out.write("\t\t\tvar address = $(\"#address\").val();\r\n");
      out.write("\t\t\tvar idCardNum =$(\"#idCardNum\").val();\r\n");
      out.write("\t\t\tvar idCardPicUrl = $(\"#idCardPicUrl\").files;\r\n");
      out.write("\t\t\tvar businessLicenseUrl = $(\"#businessLicenseUrl\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//前端校验参数有效性\r\n");
      out.write("\t\t\t//真实姓名不能为空且长度不能超过10\r\n");
      out.write("\t\t\tif(bossName==\"\"||bossName.length>=10){\r\n");
      out.write("\t\t\t\talert(\"请输入正确格式的真实姓名\");\r\n");
      out.write("\t\t\t\t//return ;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//手机号码格式校验\r\n");
      out.write("\t\t\tvar checkPhone = /^(((13[0-9]{1})|(15[0-9]{1})|17[0-9]{1}|(18[0-9]{1}))+\\d{8})$/;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(!checkPhone.test(phone)){\r\n");
      out.write("\t\t\t\talert(\"请输入正确格式的手机号码\");\r\n");
      out.write("\t\t\t\t//return ;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar checkIdCard = /^\\d{6}(18|19|20)?\\d{2}(0[1-9]|1[12])(0[1-9]|[12]\\d|3[01])\\d{3}(\\d|X)$/i;\r\n");
      out.write("\t\t\tif(!checkIdCard.test(idCardNum)){\r\n");
      out.write("\t\t\t\talert(\"请输入正确格式的身份证\");\r\n");
      out.write("\t\t\t\t//return ;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar point = idCardPicUrl[0].name.lastIndexOf(\".\");\r\n");
      out.write("\t\t\tvar fileNameLen = idCardPicUrl[0].name.length;\r\n");
      out.write("\t\t\tvar suffix = idCardPicUrl[0].name.substring(point+1,fileNameLen);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(suffix!=\"jpg\"&&suffix!=\"png\"&&suffix!=\"ipeg\"\t){\r\n");
      out.write("\t\t\t\talert(\"请上传ipg或png类型且不超过2m的照片\");\r\n");
      out.write("\t\t\t\treturn ;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\talert(idCardPicUrl[0].name.size);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\talert(bossName+\",\"+phone+\",\"+address+\",\"+idCardPicUrl+\",\"+businessLicenseUrl);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("\t    \r\n");
      out.write("    <title>加盟</title>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<!--loading页开始-->\r\n");
      out.write("<div class=\"loading\">\r\n");
      out.write("\t<div class=\"loader\">\r\n");
      out.write("        <div class=\"loader-inner pacman\">\r\n");
      out.write("          <div></div>\r\n");
      out.write("          <div></div>\r\n");
      out.write("          <div></div>\r\n");
      out.write("          <div></div>\r\n");
      out.write("          <div></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--loading页结束-->\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div class=\"headertwo clearfloat\" id=\"header\">\r\n");
      out.write("\t\t\t<a href=\"javascript:history.go(-1)\" class=\"fl box-s\"><i class=\"iconfont icon-arrow-l fl\"></i></a>\r\n");
      out.write("\t\t\t<p class=\"fl\">加盟</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"clearfloat\" id=\"main\">\r\n");
      out.write("\t\t\t<div class=\"recom-tit recom-titwo clearfloat box-s\">\r\n");
      out.write("\t    \t\t<p>加盟政策</p>\r\n");
      out.write("\t    \t</div>\r\n");
      out.write("\t    \t<div class=\"join clearfloat box-s\">\n");
      out.write("\t    \t\t<div class=\"top clearfloat box-s\">\n");
      out.write("\t    \t\t\t<div class=\"tu\">\n");
      out.write("\t    \t\t\t\t<img src=\"upload/3.jpg\"/>\n");
      out.write("\t    \t\t\t</div>\r\n");
      out.write("\t    \t\t\t\r\n");
      out.write("\t    \t\t\t<p class=\"tit\">经销商加盟</p>\r\n");
      out.write("\t    \t\t\t<p class=\"fu-tit\">\r\n");
      out.write("\t    \t\t\t\t我们一直秉承顾客第一的核心价值观，以亲切、专业的服务给顾客带来优质\r\n");
      out.write("\t\t\t\t\t\t的体验；公司自营业以来，已经有成熟的管理模式和经营模式，加盟可享受\r\n");
      out.write("\t\t\t\t\t\t到公司的提供的宝贵资源，只要您有服务，有质量，我们便能确保每个\r\n");
      out.write("\t\t\t\t\t\t加盟商都成为享受更好的平台！我们的加盟政策的制定我们经过了公司运营团队及\r\n");
      out.write("\t\t\t\t\t\t行业专业人士的反复论证，并在实际操作过程中听取广大加盟商朋友的建议。\r\n");
      out.write("\t    \t\t\t</p>\n");
      out.write("\t    \t\t</div>\n");
      out.write("\t    \t</div>\r\n");
      out.write("\t    \t<div class=\"recom-tit recom-titwo clearfloat box-s\">\r\n");
      out.write("\t    \t\t<p>在线加盟申请</p>\r\n");
      out.write("\t    \t</div>\r\n");
      out.write("\t    \t<form action=\"\">\r\n");
      out.write("\t    \t<div class=\"land-ctent clearfloat\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"box-s clearfloat\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"tit fl\">姓名</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"formControls\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"bossName\" id=\"bossName\" value=\"\" placeholder=\"您的姓名\" class=\"fl\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"box-s clearfloat\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"tit fl\">手机号</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"formControls\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"input-text\" name=\"PhoneNum\" id=\"PhoneNum\" datatype=\"*\" value=\"\" placeholder=\"您的手机号码\"  nullmsg=\"手机号码必填\" errormsg=\"请输入正确的手机号码\"\t>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"box-s clearfloat\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"tit fl\">身份证</p>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"idCardNum\" id=\"idCardNum\" value=\"\" placeholder=\"您的身份证号码\" class=\"fl\" />\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"box-s clearfloat\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"tit fl\">详细地址</p>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"address\" id=\"address\" value=\"\" placeholder=\"市、区/县、街道\" class=\"fl\" />\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"box-s clearfloat\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"tit fl\">身份证照片</p>\r\n");
      out.write("\t\t\t\t\t\t<span id=\"spanButtonPlaceholder\" ></span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"box-s clearfloat\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"tit tit2 fl\">营业执照</p>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"file\" name=\"businessLicenseUrl\" id=\"businessLicenseUrl\" value=\"\"  class=\"easyui-filebox\" style=\"buttonAlign:right\" accept=\"image/png, image/jpeg, image/gif, image/jpg\"/>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<a href=\"#loginmodal\" id=\"modaltrigger\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" name=\"btnSubmit\" id=\"btnSubmit\" value=\"提交申请\" class=\"btn\" />\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--弹窗内容 star-->\r\n");
      out.write("\t    <div id=\"loginmodal\" class=\"box-s loginmodaltwo\" style=\"display:none;\">\t    \t\r\n");
      out.write("\t\t\t<form id=\"loginform\" name=\"loginform\" method=\"post\" action=\"\">\t\t\r\n");
      out.write("\t\t\t\t<div class=\"center\"><input type=\"submit\" name=\"loginbtn\" id=\"loginbtn\" class=\"flatbtn-blutwo hidemodal\" value=\"\" tabindex=\"3\"></div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<div class=\"bottom clearfloat box-s\">\r\n");
      out.write("\t\t\t\t<div class=\"login-dui clearfloat\">\r\n");
      out.write("\t\t\t\t\t<p class=\"tu\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/dui.png\"/>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<p class=\"tit\">\r\n");
      out.write("\t\t\t\t\t\t恭喜您，申请成功！\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<p class=\"fu-tit\">\r\n");
      out.write("\t\t\t\t\t\t请保持所填号码手机的通话畅通状态，我们的客服将会在48小时内与您取得联系。\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input type=\"button\" name=\"\" id=\"\" value=\"好的，我知道了\" class=\"btn btn1\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t    <!--弹窗内容 end-->\r\n");
      out.write("\t</body>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-1.8.3.min.js\" ></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"slick/slick.min.js\" ></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery.leanModal.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/tchuang.js\" ></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/hmt.js\" ></script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
